on:
  push:
    branches: [ chore/gh-actions-update ]

name: Release EarlyBird

jobs:
  build:
    name: Build and Tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump-version.outputs.new_tag }}
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build project
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
         - name: earlybird-binaries
           path: ./binaries/
           if-no-files-found: error
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: .*
          INITIAL_VERSION: 2.0.0
  release:
    needs: build
    name: Tag and Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.build.outputs.new_tag }}
          draft: false
          prerelease: false
  publishLinux:
    needs: [build, release]
    name: Publish Linux Asset
    runs-on: ubuntu-latest
    steps:
      - name: Download earlybird artifacts
        uses: actions/download-artifact@v2
        with:
          - name: earlybird-binaries
      - name: Upload Linux Release Asset
        id: upload-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./binaries/go-earlybird-linux
          asset_name: go-earlybird-linux
          asset_content_type: application/octet-stream
  publishmacOS:
    needs: [build, release]
    name: Publish MacOS Asset
    runs-on: ubuntu-latest
    steps:
      - name: Download earlybird artifacts
        uses: actions/download-artifact@v2
        with:
          - name: earlybird-binaries
      - name: Upload macOS Release Asset
        id: upload-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./binaries/go-earlybird
          asset_name: go-earlybird-macos
          asset_content_type: application/octet-stream
  publishWindows:
    needs: [build, release]
    name: Publish Windows Asset
    runs-on: ubuntu-latest
    steps:
      - name: Download earlybird artifacts
        uses: actions/download-artifact@v2
        with:
          - name: earlybird-binaries
      - name: Upload Windows Release Asset
        id: upload-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./binaries/go-earlybird.exe
          asset_name: go-earlybird.exe
          asset_content_type: application/x-msdownload
